#!/bin/bash

#Maintener Rodrigo Miguel rodrigomvi@algartech.com 
machines="IP IP"
user=user
password=pass

for host in $machines;
do
sshpass -p$password ssh -o StrictHostKeyChecking=no -n $user@$host cat access.201[67]????-?????? | grep * | grep BIND > output-$host.txt ; done
