#!/bin/bash

#Maintener Rodrigo Miguel rodrigomvi@algartech.com 
machines="IPS separados por espaço"
user=user
password=pass

for host in $machines;
do

#sshpass -pRedeslpi ssh-copy-id rodrigo.rmv@10.2.192.29

sshpass -p$password ssh-copy-id -f -o StrictHostKeyChecking=no -n $user@$host ; done

