#!/bin/bash

#Maintener Rodrigo Miguel rodrigomvi@algartech.com 
#Required
sudo echo 'deb https://get.docker.com/ubuntu docker main' sudo > /etc/apt/sources.list.d/docker.list
vim /etc/apt/sources.list.d/docker.list:
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
sudo apt-get update
sudo apt-get install -y docker.io cgroup-lite apparmor
sudo usermod -a -G docker rodrigo.rmv
sudo service docker start
sudo service docker status
